include: package:flutter_lints/flutter.yaml

linter: 
  rules:
    await_only_futures: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_const_constructors_in_immutables: warning
    avoid_unnecessary_containers: warning
    prefer_final_locals: info

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
